# Generated by Django 5.0.6 on 2024-07-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfferLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=250)),
                ('KRA', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('salary', models.CharField(max_length=250)),
            ],
        ),
    ]
